@Library('corda-shared-build-pipeline-steps@5.0') _

cordaPipeline(
    publishRepoPrefix: '',
    slimBuild: true,
    runUnitTests: false,
    dedicatedJobForSnykDelta: false,
    slackChannel: '#corda-corda5-dev-ex-build-notifications',
    )
